In [514]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import boto3
import json
import datetime
import pytz

Capture live data from S3

Get signatures calling function

In [515]:
# bucket_name = 'kishoredkjul18'
# s3_client = boto3.client('s3')
# sig = pd.DataFrame()
# val_dict = {}
# time_modified = datetime.datetime(2020,1,1)
# time_modified = time_modified.astimezone(pytz.timezone("Asia/Kolkata"))
# for i in range(10):
#     x=0
#     while (x<60):
#             latest_ver = s3_client.get_object(Bucket = 'kishoredkjul18', Key='Id6')
#             last_modified = latest_ver['LastModified']
#             last_modified = last_modified.astimezone(pytz.timezone("Asia/Kolkata")) 
#             if last_modified>time_modified:
#                 json_body = json.loads(latest_ver['Body'].read()[0:-1].decode('utf8'))
#                 val_dict[f'A{x+1}'] = json_body['A1']
#                 val_dict[f'PF{x+1}'] = json_body['PF1']
#                 time_modified = last_modified
#                 x+=1
#     df2 = pd.DataFrame(val_dict,index=[i])
#     sig = sig.append(df2)

In [516]:
sig_static = pd.read_csv('static.csv')
sig_1led = pd.read_csv('1 led.csv')
sig_2led = pd.read_csv('2 led.csv')
sig_fan = pd.read_csv('fan.csv')
sig_fridge = pd.read_csv('fridge.csv')
sig_washer1 = pd.read_csv('washingmachine 1.csv')
sig_washer2 = pd.read_csv('washingmachine 2.csv')
sig_washer3 = pd.read_csv('washingmachine 3.csv')
sig_washer4 = pd.read_csv('washingmachine 4.csv')
sig_laptop = pd.read_csv('laptop.csv')
sig_induction = pd.read_csv('induction.csv')
sig_toaster = pd.read_csv('toaster.csv')
sig_fan_fridge = pd.read_csv('fan + fridge.csv')

combining washing machine stages

lets see static values


In [517]:
sig_static

A1   PF1    A2   PF2    A3   PF3    A4   PF4    A5   PF5  ...   A56  \
0  30.0  0.83  30.0  0.83  30.0  0.83  30.0  0.83  30.0  0.83  ...  29.0   
1  30.0  0.83  30.0  0.83  29.0  0.83  29.0  0.83  30.0  0.82  ...  30.0   
2  30.0  0.83  30.0  0.83  30.0  0.83  30.0  0.83  30.0  0.83  ...  29.0   
3  30.0  0.83  29.0  0.83  30.0  0.83  30.0  0.83  29.0  0.83  ...  29.0   
4  30.0  0.83  30.0  0.84  29.0  0.83  30.0  0.83  30.0  0.83  ...  29.0   
5  29.0  0.83  29.0  0.83  30.0  0.83  29.0  0.83  30.0  0.83  ...  29.0   
6  30.0  0.83  29.0  0.83  30.0  0.83  29.0  0.83  30.0  0.83  ...  29.0   
7  29.0  0.83  30.0  0.83  29.0  0.83  29.0  0.83  29.0  0.83  ...  30.0   
8  30.0  0.82  30.0  0.83  29.0  0.83  29.0  0.83  29.0  0.83  ...  30.0   
9  30.0  0.83  29.0  0.83  29.0  0.83  30.0  0.83  29.0  0.83  ...  29.0   

   PF56   A57  PF57   A58  PF58   A59  PF59   A60  PF60  
0  0.84  30.0  0.83  30.0  0.84  29.0  0.83  30.0  0.83  
1  0.83  30.0  0.83  30.0  0.83  30.0  0.83  30.0  0.83  
2  0.83  30.0  0.83  30.0  0.83  29.0  0.83  29.0  0.83  
3  0.83  30.0  0.83  29.0  0.83  29.0  0.83  30.0  0.83  
4  0.83  30.0  0.83  30.0  0.83  30.0  0.83  30.0  0.83  
5  0.84  30.0  0.83  30.0  0.83  30.0  0.83  30.0  0.84  
6  0.83  30.0  0.83  30.0  0.82  30.0  0.82  30.0  0.83  
7  0.83  30.0  0.84  30.0  0.84  30.0  0.83  30.0  0.83  
8  0.84  30.0  0.84  30.0  0.83  30.0  0.84  30.0  0.83  
9  0.82  30.0  0.83  30.0  0.83  30.0  0.82  29.0  0.83  

[10 rows x 120 columns]

In [518]:
calib = np.array(sig_static.mean())

plot usage of two leds 15w and 14w

In [519]:
sig_2led = sig_2led.subtract(calib)

plot usage of 15w bulb

In [520]:
sig_1led = sig_1led.subtract(calib)

In [521]:
sig_2led = sig_2led.subtract(sig_1led)

if Active Power = (V x I) / sqrt(2) 

A1 -> 12 x sqrt(2) = 16.97 W **rating** =15W 

the fan + fridge readings

In [523]:
sig_fan_fridge = sig_fan_fridge.subtract(calib)

fan readings

In [524]:
sig_fan = sig_fan.subtract(calib)

In [525]:
sig_fridge = sig_fridge.subtract(calib)

**frdige had two states running and idle**

In [526]:
new_fridge_fan = sig_fridge.add(sig_fan)

In [527]:
new_fridge_fan.mean()

A1      92.600
PF1     -0.002
A2      92.600
PF2     -0.007
A3      92.900
         ...  
PF58    -0.019
A59     97.500
PF59    -0.027
A60     97.600
PF60    -0.033
Length: 120, dtype: float64

In [528]:
sig_fan_fridge.mean()

A1      50.400
PF1      0.088
A2      50.700
PF2      0.086
A3      50.700
         ...  
PF58     0.085
A59     50.500
PF59     0.085
A60     50.400
PF60     0.085
Length: 120, dtype: float64

In [529]:
sig_induction = sig_induction.subtract(calib)

In [530]:
sig_laptop = sig_laptop.subtract(calib)

In [531]:
sig_toaster = sig_toaster.subtract(calib)

In [532]:
sig_washer1 = sig_washer1.subtract(calib)

In [533]:
sig_washer2 = sig_washer2.subtract(calib)

In [534]:
sig_washer3 = sig_washer3.subtract(calib)

In [535]:
sig_static['target']=' '

In [536]:
sig_2led['target'] = '14w led '

In [537]:
sig_1led['target'] = '15w led '

In [538]:
sig_fan['target'] = 'fan '

In [539]:
sig_fridge['target']= 'fridge '

In [540]:
sig_induction['target'] = 'induction '

In [541]:
sig_toaster['target'] = 'toaster '

In [542]:
sig_washer1['target'] = 'washing machine 1 '

In [543]:
sig_washer2['target'] = 'washing machine 2 '

In [544]:
sig_washer3['target'] = 'washing machine 3 '

In [545]:
sig_laptop['target'] = 'laptop '

In [546]:
sig_fan_fridge['target'] = 'real fan fridge '

In [547]:
new_fridge_fan['target'] = 'derived fan fridge '

In [548]:
large_df = pd.DataFrame()
large_df = large_df.append(sig_1led)
large_df = large_df.append(sig_2led)
large_df = large_df.append(sig_fan)
large_df = large_df.append(sig_fan_fridge)
large_df = large_df.append(sig_fridge)
large_df = large_df.append(sig_induction)
large_df = large_df.append(sig_laptop)
large_df = large_df.append(sig_static)
large_df = large_df.append(sig_toaster)
large_df = large_df.append(sig_washer1)

In [550]:
column_names = sig_fan_fridge.columns
column_names

Index(['A1', 'PF1', 'A2', 'PF2', 'A3', 'PF3', 'A4', 'PF4', 'A5', 'PF5',
       ...
       'PF56', 'A57', 'PF57', 'A58', 'PF58', 'A59', 'PF59', 'A60', 'PF60',
       'target'],
      dtype='object', length=121)

In [551]:
from itertools import combinations 

In [552]:
sig_washing_machine = pd.DataFrame()
sig_washing_machine = sig_washing_machine.append(sig_washer1[0:4])
sig_washing_machine = sig_washing_machine.append(sig_washer2[0:3])
sig_washing_machine = sig_washing_machine.append(sig_washer3[0:3])

**note this code**

In [553]:
large_df = large_df.append(sig_washing_machine)
large_df = large_df.append(sig_washer2)
large_df = large_df.append(sig_washer3)
large_df = large_df.append(sig_washer4)

In [554]:
devices = np.array([sig_static.to_numpy(),
          sig_1led.to_numpy(),
          sig_2led.to_numpy(),
          sig_fan.to_numpy(),
          sig_fridge.to_numpy(),
          sig_washing_machine.to_numpy(),
          sig_laptop.to_numpy(),
          sig_induction.to_numpy(),
          sig_toaster.to_numpy(),
          sig_fan_fridge.to_numpy()])

In [555]:
two_combo = combinations(devices,2)

In [556]:
two_combo

In [557]:
large_df_2 = pd.DataFrame()
for combos in two_combo:
    z= combos[0]+combos[1]
    df = pd.DataFrame(z,columns = column_names)
    large_df_2 = large_df_2.append(df)

In [558]:
large_df_2

A1    PF1     A2    PF2    A3   PF3    A4   PF4     A5    PF5  ...  \
0    44.2  0.921   44.4  0.919  44.5  0.92  44.5  0.92   44.4  0.921  ...   
1    44.2  0.921   44.4  0.919  43.5  0.92  43.5  0.92   44.4  0.911  ...   
2    44.2  0.921   44.4  0.919  44.5  0.92  44.5  0.92   44.4  0.921  ...   
3    44.2  0.921   43.4  0.919  44.5  0.92  44.5  0.92   43.4  0.921  ...   
4    44.2  0.921   45.4  0.929  43.5  0.92  44.5  0.92   44.4  0.921  ...   
..    ...    ...    ...    ...   ...   ...   ...   ...    ...    ...  ...   
5   758.4  0.262  759.8  0.258   760  0.26   759  0.26  758.8  0.262  ...   
6   756.4  0.262  757.8  0.258   758  0.26   758  0.26  757.8  0.262  ...   
7   756.4  0.262  756.8  0.258   757  0.25   757  0.25  755.8  0.262  ...   
8   759.4  0.252  760.8  0.258   762  0.26   762  0.26  760.8  0.262  ...   
9   758.4  0.252  760.8  0.248   760  0.25   760  0.25  759.8  0.252  ...   

     PF56  A57   PF57    A58   PF58    A59   PF59    A60   PF60  \
0   0.928   44  0.918   44.1  0.919   43.3  0.921   44.2  0.919   
1   0.918   44  0.918   44.1  0.919   44.3  0.921   44.2  0.919   
2   0.918   44  0.918   44.1  0.919   43.3  0.921   43.2  0.919   
3   0.918   44  0.918   43.1  0.919   43.3  0.921   44.2  0.919   
4   0.918   44  0.918   44.1  0.919   44.3  0.921   44.2  0.919   
..    ...  ...    ...    ...    ...    ...    ...    ...    ...   
5   0.256  755  0.256  755.2  0.258  756.6  0.262  756.4  0.258   
6   0.246  757  0.256  757.2  0.248  756.6  0.252  757.4  0.258   
7   0.256  757  0.246  756.2  0.248  760.6  0.252  760.4  0.248   
8   0.256  758  0.246  759.2  0.248  759.6  0.252  758.4  0.248   
9   0.256  759  0.256  759.2  0.258  759.6  0.252  758.4  0.258   

                      target  
0                   15w led   
1                   15w led   
2                   15w led   
3                   15w led   
4                   15w led   
..                       ...  
5   toaster real fan fridge   
6   toaster real fan fridge   
7   toaster real fan fridge   
8   toaster real fan fridge   
9   toaster real fan fridge   

[450 rows x 121 columns]

In [559]:
large_df_3 = pd.DataFrame()
three_combo = combinations(devices,3)
for combos in three_combo:
    z= combos[0]+combos[1]+combos[2]
    df = pd.DataFrame(z,columns = column_names)
    large_df_3 = large_df_3.append(df)

In [560]:
large_df_3

A1    PF1      A2    PF2      A3   PF3      A4   PF4      A5    PF5  \
0     56.2  0.941    56.4  0.939    56.5  0.94    56.5  0.94    56.4  0.941   
1     56.2  0.941    56.4  0.939    55.5  0.94    55.5  0.94    56.4  0.931   
2     56.2  0.941    56.4  0.939    56.5  0.94    56.5  0.94    56.4  0.941   
3     56.2  0.941    55.4  0.939    56.5  0.94    56.5  0.94    55.4  0.941   
4     56.2  0.941    56.4  0.949    55.5  0.94    56.5  0.94    56.4  0.941   
..     ...    ...     ...    ...     ...   ...     ...   ...     ...    ...   
5    779.6  0.183   780.2  0.177  1474.5  0.42  1483.5  0.42  1385.2  0.373   
6   1483.6  0.423   779.2  0.177   779.5  0.18  1287.5  0.41  1492.2  0.423   
7   1488.6  0.423   927.2  0.057   777.5  0.17   777.5  0.17  1415.2  0.423   
8    827.6  0.173  1489.2  0.417  1496.5  0.42   801.5 -0.05   781.2  0.183   
9   1436.6  0.413  1560.2  0.407  1499.5  0.39   780.5  0.17   780.2  0.173   

    ...   PF56   A57   PF57     A58   PF58     A59   PF59     A60   PF60  \
0   ...  0.948    56  0.938    56.1  0.949    55.3  0.941    56.2  0.939   
1   ...  0.938    56  0.938    56.1  0.939    56.3  0.941    56.2  0.939   
2   ...  0.938    56  0.938    56.1  0.939    55.3  0.941    55.2  0.939   
3   ...  0.938    56  0.938    55.1  0.939    55.3  0.941    56.2  0.939   
4   ...  0.938    56  0.938    56.1  0.939    56.3  0.941    56.2  0.939   
..  ...    ...   ...    ...     ...    ...     ...    ...     ...    ...   
5   ...  0.414   775  0.174   775.3  0.177  1390.9  0.423  1491.6  0.417   
6   ...  0.404   784  0.014   777.3  0.167   776.9  0.173  1463.6  0.417   
7   ...  0.324  1497  0.404  1488.3  0.407   781.9  0.133   780.6  0.167   
8   ...  0.414  1548  0.404   970.3  0.067   779.9  0.173   778.6  0.167   
9   ...  0.174  1488  0.414  1553.3  0.417   983.9  0.093   778.6  0.177   

                                target  
0                     15w led 14w led   
1                     15w led 14w led   
2                     15w led 14w led   
3                     15w led 14w led   
4                     15w led 14w led   
..                                 ...  
5   induction toaster real fan fridge   
6   induction toaster real fan fridge   
7   induction toaster real fan fridge   
8   induction toaster real fan fridge   
9   induction toaster real fan fridge   

[1200 rows x 121 columns]

In [561]:
large_df_4 = pd.DataFrame()
four_combo = combinations(devices,4)
for combos in four_combo:
    z= combos[0]+combos[1]+combos[2]+combos[3]
    df = pd.DataFrame(z,columns = column_names)
    large_df_4 = large_df_4 .append(df)

In [562]:
large_df_4

A1    PF1      A2    PF2    A3   PF3    A4   PF4      A5    PF5  ...  \
0    108.4  1.032   108.8  1.018   109  1.02   109  1.02   108.8  1.022  ...   
1    109.4  1.022   108.8  1.018   108  1.02   109  1.02   107.8  1.012  ...   
2    107.4  1.022   107.8  1.028   108  1.03   108  1.02   107.8  1.022  ...   
3    107.4  1.022   106.8  1.018   108  1.02   108  1.02   106.8  1.022  ...   
4    107.4  1.022   107.8  1.028   107  1.02   108  1.02   107.8  1.022  ...   
..     ...    ...     ...    ...   ...   ...   ...   ...     ...    ...  ...   
5    835.8  0.054   836.6  0.046  1531  0.29  1540  0.29  1442.6  0.244  ...   
6   1539.8  0.284   836.6  0.046   836  0.05  1345  0.28  1548.6  0.294  ...   
7   1544.8  0.294   987.6 -0.074   844  0.02   834  0.04  1472.6  0.304  ...   
8    887.8  0.044  1549.6  0.286  1557  0.29   865 -0.19   841.6  0.054  ...   
9   1579.8  0.324  1702.6  0.316  1645   0.3   914  0.08   912.6  0.084  ...   

     PF56   A57   PF57     A58   PF58     A59   PF59     A60   PF60  \
0   1.026   108  1.016   107.2  1.028   107.6  1.022   108.4  1.018   
1   1.016   107  1.016   107.2  1.018   107.6  1.022   107.4  1.018   
2   1.016   107  1.016   107.2  1.018   106.6  1.022   106.4  1.018   
3   1.016   107  1.016   106.2  1.018   106.6  1.022   107.4  1.018   
4   1.026   107  1.026   107.2  1.028   107.6  1.022   107.4  1.018   
..    ...   ...    ...     ...    ...     ...    ...     ...    ...   
5   0.282   831  0.042   831.4  0.046  1447.2  0.284  1548.8  0.286   
6   0.272   841 -0.108   833.4  0.046   833.2  0.054  1520.8  0.286   
7   0.182  1556  0.262  1550.4  0.276   846.2  0.004   839.8  0.036   
8   0.302  1686  0.312  1112.4 -0.034   915.2  0.084   917.8  0.076   
9   0.092  1615  0.332  1690.4  0.326  1112.2  0.014   923.8  0.096   

                                       target  
0                        15w led 14w led fan   
1                        15w led 14w led fan   
2                        15w led 14w led fan   
3                        15w led 14w led fan   
4                        15w led 14w led fan   
..                                        ...  
5   laptop induction toaster real fan fridge   
6   laptop induction toaster real fan fridge   
7   laptop induction toaster real fan fridge   
8   laptop induction toaster real fan fridge   
9   laptop induction toaster real fan fridge   

[2100 rows x 121 columns]

In [563]:
large_df_5 = pd.DataFrame()
five_combo = combinations(devices,5)
for combos in five_combo:
    z= combos[0]+combos[1]+combos[2]+combos[3]+combos[4]
    df = pd.DataFrame(z,columns = column_names)
    large_df_5 = large_df_5.append(df)

In [565]:
large_df_6 = pd.DataFrame()
six_combo = combinations(devices,6)
for combos in six_combo:
    z= combos[0]+combos[1]+combos[2]+combos[3]+combos[4]+combos[5]
    df = pd.DataFrame(z,columns = column_names)
    large_df_6 = large_df_6.append(df)

In [566]:
large_df_7 = pd.DataFrame()
seven_combo = combinations(devices,7)
for combos in seven_combo:
    z= combos[0]+combos[1]+combos[2]+combos[3]+combos[4]+combos[5]+combos[6]
    df = pd.DataFrame(z,columns = column_names)
    large_df_7 = large_df_7.append(df)

In [567]:
large_df_8 = pd.DataFrame()
eight_combo = combinations(devices,8)
for combos in eight_combo:
    z= combos[0]+combos[1]+combos[2]+combos[3]+combos[4]+combos[5]+combos[6]+ combos[7]
    df = pd.DataFrame(z,columns = column_names)
    large_df_8 = large_df_8.append(df)

In [568]:
large_df_9 = pd.DataFrame()
nine_combo = combinations(devices,9)
for combos in nine_combo:
    z= combos[0]+combos[1]+combos[2]+combos[3]+combos[4]+combos[5]+combos[6]+ combos[7]+combos[8]
    df = pd.DataFrame(z,columns = column_names)
    large_df_9 = large_df_9.append(df)

In [569]:
large_df_10 = pd.DataFrame()
ten_combo = combinations(devices,10)
for combos in ten_combo:
    z= combos[0]+combos[1]+combos[2]+combos[3]+combos[4]+combos[5]+combos[6]+ combos[7]+combos[8]+ combos[9]
    df = pd.DataFrame(z,columns = column_names)
    large_df_10 = large_df_10.append(df)

In [499]:
test_df = large_df_2.copy()

In [607]:
large_df.to_csv('large_df.csv',index=False)
large_df_2.to_csv('large_df_2.csv',index=False)
large_df_3.to_csv('large_df_3.csv',index=False)
large_df_4.to_csv('large_df_4.csv',index=False)
large_df_5.to_csv('large_df_5.csv',index=False)
large_df_6.to_csv('large_df_6.csv',index=False)
large_df_7.to_csv('large_df_7.csv',index=False)
large_df_8.to_csv('large_df_8.csv',index=False)
large_df_9.to_csv('large_df_9.csv',index=False)
large_df_10.to_csv('large_df_10.csv',index=False)

In [612]:
large_df_1= pd.read_csv('large_df.csv')
large_df_2 = pd.read_csv('large_df_2.csv')
large_df_3 = pd.read_csv('large_df_3.csv')
large_df_4 = pd.read_csv('large_df_4.csv')
large_df_5 = pd.read_csv('large_df_5.csv')
large_df_6 = pd.read_csv('large_df_6.csv')
large_df_7 = pd.read_csv('large_df_7.csv')
large_df_8 = pd.read_csv('large_df_8.csv')
large_df_9 = pd.read_csv('large_df_9.csv')
large_df_10 = pd.read_csv('large_df_10.csv')

# Model Creation


In [631]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

X = large_df_10.drop('target', axis=1)
y = large_df_10['target']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
clf = RandomForestClassifier()

clf.fit(X_train,y_train)
clf.score(X_test,y_test)

1.0

In [632]:
import pickle
pickle.dump(clf,open('minionmodel_10.pkl','wb'))

In [633]:
minionmodel_1 = pickle.load(open('minionmodel_1.pkl','rb'))
minionmodel_2 = pickle.load(open('minionmodel_2.pkl','rb'))
minionmodel_3 = pickle.load(open('minionmodel_3.pkl','rb'))
minionmodel_4 = pickle.load(open('minionmodel_4.pkl','rb'))
minionmodel_5 = pickle.load(open('minionmodel_5.pkl','rb'))
minionmodel_6 = pickle.load(open('minionmodel_6.pkl','rb'))
minionmodel_7 = pickle.load(open('minionmodel_7.pkl','rb'))
minionmodel_8 = pickle.load(open('minionmodel_8.pkl','rb'))
minionmodel_9 = pickle.load(open('minionmodel_9.pkl','rb'))
minionmodel_10 = pickle.load(open('minionmodel_10.pkl','rb'))


# test with live data

In [634]:
# bucket_name = 'kishoredkjul18'
# s3_client = boto3.client('s3')
# sig = pd.DataFrame()
# val_dict = {}
# time_modified = datetime.datetime(2020,1,1)
# time_modified = time_modified.astimezone(pytz.timezone("Asia/Kolkata"))
# for i in range(10):
#     x=0
#     while (x<60):
#             latest_ver = s3_client.get_object(Bucket = 'kishoredkjul18', Key='Id6')
#             last_modified = latest_ver['LastModified']
#             last_modified = last_modified.astimezone(pytz.timezone("Asia/Kolkata")) 
#             if last_modified>time_modified:
#                 json_body = json.loads(latest_ver['Body'].read()[0:-1].decode('utf8'))
#                 val_dict[f'A{x+1}'] = json_body['A1']
#                 val_dict[f'PF{x+1}'] = json_body['PF1']
#                 time_modified = last_modified
#                 x+=1
#     df2 = pd.DataFrame(val_dict,index=[i])
#     sig = sig.append(df2)

In [635]:
clf.predict(sig)

array([' 15w led 14w led fan fridge washing machine 3 laptop induction toaster real fan fridge ',
       ' 15w led 14w led fan fridge washing machine 3 laptop induction toaster real fan fridge ',
       ' 15w led 14w led fan fridge washing machine 3 laptop induction toaster real fan fridge ',
       ' 15w led 14w led fan fridge washing machine 3 laptop induction toaster real fan fridge ',
       ' 15w led 14w led fan fridge washing machine 3 laptop induction toaster real fan fridge ',
       ' 15w led 14w led fan fridge washing machine 3 laptop induction toaster real fan fridge ',
       ' 15w led 14w led fan fridge washing machine 3 laptop induction toaster real fan fridge ',
       ' 15w led 14w led fan fridge washing machine 3 laptop induction toaster real fan fridge ',
       ' 15w led 14w led fan fridge washing machine 3 laptop induction toaster real fan fridge ',
       ' 15w led 14w led fan fridge washing machine 3 laptop induction toaster real fan fridge '],
      dtype=object)

In [636]:
sig

A1   PF1     A2   PF2     A3   PF3     A4   PF4     A5   PF5  ...  \
0  119.0  0.92  119.0  0.92  119.0  0.92  119.0  0.92  119.0  0.92  ...   
1  118.0  0.92  120.0  0.92  120.0  0.92  120.0  0.92  121.0  0.91  ...   
2  117.0  0.92  118.0  0.92  119.0  0.92  118.0  0.92  118.0  0.92  ...   
3  117.0  0.92  116.0  0.92  116.0  0.92  117.0  0.92  116.0  0.92  ...   
4  115.0  0.92  116.0  0.92  115.0  0.92  115.0  0.92  116.0  0.92  ...   
5  117.0  0.92  118.0  0.92  124.0  0.91  117.0  0.92  117.0  0.92  ...   
6  117.0  0.92  118.0  0.92  118.0  0.92  118.0  0.92  119.0  0.92  ...   
7  116.0  0.92  115.0  0.92  116.0  0.92  117.0  0.92  117.0  0.92  ...   
8  116.0  0.92  116.0  0.92  116.0  0.92  117.0  0.92  116.0  0.92  ...   
9  115.0  0.92  115.0  0.92  115.0  0.92  115.0  0.92  115.0  0.92  ...   

     A56  PF56    A57  PF57    A58  PF58    A59  PF59    A60  PF60  
0  121.0  0.92  119.0  0.92  119.0  0.92  119.0  0.92  121.0  0.91  
1  117.0  0.92  118.0  0.92  117.0  0.92  118.0  0.92  118.0  0.92  
2  116.0  0.92  117.0  0.92  116.0  0.92  116.0  0.92  115.0  0.92  
3  115.0  0.92  115.0  0.92  116.0  0.92  115.0  0.92  115.0  0.92  
4  117.0  0.92  117.0  0.92  117.0  0.92  117.0  0.92  117.0  0.92  
5  118.0  0.92  119.0  0.92  118.0  0.92  119.0  0.92  118.0  0.92  
6  117.0  0.92  117.0  0.92  116.0  0.92  115.0  0.92  115.0  0.92  
7  116.0  0.92  116.0  0.92  116.0  0.92  115.0  0.92  116.0  0.92  
8  116.0  0.92  118.0  0.92  123.0  0.91  117.0  0.92  116.0  0.92  
9  115.0  0.92  115.0  0.92  115.0  0.92  115.0  0.92  115.0  0.92  

[10 rows x 120 columns]

14w laptop fan 15w fridge

make clusters.....

In [653]:
minionmodel_1.predict_proba(sig)

array([[0.86, 0.  , 0.  , 0.02, 0.  , 0.01, 0.  , 0.  , 0.  , 0.01, 0.06,
        0.04],
       [0.86, 0.  , 0.  , 0.02, 0.  , 0.01, 0.  , 0.  , 0.  , 0.01, 0.06,
        0.04],
       [0.86, 0.  , 0.  , 0.02, 0.  , 0.01, 0.  , 0.  , 0.  , 0.01, 0.06,
        0.04],
       [0.86, 0.  , 0.  , 0.02, 0.  , 0.01, 0.  , 0.  , 0.  , 0.01, 0.06,
        0.04],
       [0.86, 0.  , 0.  , 0.02, 0.  , 0.01, 0.  , 0.  , 0.  , 0.01, 0.06,
        0.04],
       [0.86, 0.  , 0.  , 0.02, 0.  , 0.01, 0.  , 0.  , 0.  , 0.01, 0.06,
        0.04],
       [0.86, 0.  , 0.  , 0.02, 0.  , 0.01, 0.  , 0.  , 0.  , 0.01, 0.06,
        0.04],
       [0.86, 0.  , 0.  , 0.02, 0.  , 0.01, 0.  , 0.  , 0.  , 0.01, 0.06,
        0.04],
       [0.86, 0.  , 0.  , 0.02, 0.  , 0.01, 0.  , 0.  , 0.  , 0.01, 0.06,
        0.04],
       [0.86, 0.  , 0.  , 0.02, 0.  , 0.01, 0.  , 0.  , 0.  , 0.01, 0.06,
        0.04]])

In [654]:
minionmodel_2.predict_proba(sig)

array([[0.  , 0.  , 0.42, 0.  , 0.01, 0.02, 0.36, 0.  , 0.  , 0.11, 0.07,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.01, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.52, 0.  , 0.02, 0.02, 0.24, 0.  , 0.  , 0.12, 0.07,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.01, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.4 , 0.  , 0.01, 0.02, 0.38, 0.  , 0.  , 0.1 , 0.08,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  

In [655]:
minionmodel_3.predict_proba(sig)

array([[0.19, 0.01, 0.  , ..., 0.  , 0.  , 0.  ],
       [0.18, 0.02, 0.  , ..., 0.  , 0.  , 0.  ],
       [0.19, 0.01, 0.  , ..., 0.  , 0.  , 0.  ],
       ...,
       [0.19, 0.01, 0.01, ..., 0.  , 0.  , 0.  ],
       [0.18, 0.01, 0.01, ..., 0.  , 0.  , 0.  ],
       [0.19, 0.01, 0.01, ..., 0.  , 0.  , 0.  ]])

In [656]:
minionmodel_4.predict_proba(sig)

array([[0.02, 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.01, 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.02, 0.01, 0.  , ..., 0.  , 0.  , 0.  ],
       ...,
       [0.03, 0.01, 0.  , ..., 0.  , 0.  , 0.  ],
       [0.02, 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.03, 0.01, 0.  , ..., 0.  , 0.  , 0.  ]])

In [657]:
minionmodel_5.predict_proba(sig)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [658]:
minionmodel_6.predict_proba(sig)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [659]:
minionmodel_7.predict_proba(sig)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [660]:
minionmodel_8.predict_proba(sig)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [661]:
minionmodel_9.predict_proba(sig)

array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.34, 0.02, 0.09, 0.  , 0.34, 0.  ,
        0.01, 0.18, 0.  , 0.01, 0.  , 0.  , 0.01, 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.34, 0.02, 0.09, 0.  , 0.34, 0.  ,
        0.01, 0.18, 0.  , 0.01, 0.  , 0.  , 0.01, 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.34, 0.02, 0.09, 0.  , 0.34, 0.  ,
        0.01, 0.18, 0.  , 0.01, 0.  , 0.  , 0.01, 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.34, 0.02, 0.09, 0.  , 0.34, 0.  ,
        0.01, 0.18, 0.  , 0.01, 0.  , 0.  , 0.01, 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.34, 0.02, 0.09, 0.  , 0.34, 0.  ,
        0.01, 0.18, 0.  , 0.01, 0.  , 0.  , 0.01, 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.34, 0.02, 0.09, 0.  , 0.3

In [662]:
minionmodel_10.predict_proba(sig)

array([[0.28, 0.3 , 0.42],
       [0.28, 0.3 , 0.42],
       [0.28, 0.3 , 0.42],
       [0.28, 0.3 , 0.42],
       [0.28, 0.3 , 0.42],
       [0.28, 0.3 , 0.42],
       [0.28, 0.3 , 0.42],
       [0.28, 0.3 , 0.42],
       [0.28, 0.3 , 0.42],
       [0.28, 0.3 , 0.42]])

# **Try Bourke Approach**

In [686]:
# # mlp for multi-label classification
# from numpy import mean
# from numpy import std
# from sklearn.datasets import make_multilabel_classification
# from sklearn.model_selection import RepeatedKFold
# from keras.models import Sequential
# from keras.layers import Dense
# from sklearn.metrics import accuracy_score

In [687]:
# # get the dataset
# def get_dataset():
#     X, y = make_multilabel_classification(n_samples=1000, n_features=10, n_classes=3, n_labels=2, random_state=1)
#     return X, y

In [688]:
# # get the model
# def get_model(n_inputs, n_outputs):
#     model = Sequential()
#     model.add(Dense(20, input_dim=n_inputs, kernel_initializer='he_uniform', activation='relu'))
#     model.add(Dense(n_outputs, activation='sigmoid'))
#     model.compile(loss='binary_crossentropy', optimizer='adam')
#     return model

In [689]:
# # evaluate a model using repeated k-fold cross-validation
# def evaluate_model(X, y):
#     results = list()
#     n_inputs, n_outputs = X.shape[1], y.shape[1]
#     # define evaluation procedure
#     cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
#     # enumerate folds
#     for train_ix, test_ix in cv.split(X):
#         # prepare data
#         X_train, X_test = X[train_ix], X[test_ix]
#         y_train, y_test = y[train_ix], y[test_ix]
#         # define model
#         model = get_model(n_inputs, n_outputs)
#         # fit model
#         model.fit(X_train, y_train, verbose=0, epochs=100)
#         # make a prediction on the test set
#         yhat = model.predict(X_test)
#         # round probabilities to class labels
#         yhat = yhat.round()
#         # calculate accuracy
#         acc = accuracy_score(y_test, yhat)
#         # store result
#         print('>%.3f' % acc)
#         results.append(acc)
#     return results

In [690]:
# # load dataset
# X, y = get_dataset()
# # evaluate model
# results = evaluate_model(X, y)
# # summarize performance
# print('Accuracy: %.3f (%.3f)' % (mean(results), std(results)))

In [787]:
main_df = pd.DataFrame()

In [788]:
def get_data(main_df):
    devices = ['fan','fridge','led','induction','laptop','toaster','washer']
    for x in devices:
        df = pd.read_csv(f'{x}.csv')
        for y in devices:
            if y == x:
                df[f'{y}'] = 1
            else:
                df[f'{y}'] = 0
        main_df = main_df.append(df,ignore_index = True)
    return main_df

In [789]:
main_df = get_data(main_df);

In [790]:
main_df

A1   PF1     A2   PF2     A3   PF3     A4   PF4     A5   PF5  ...  \
0    82.0  0.92   82.0  0.91   82.0  0.91   82.0  0.91   82.0  0.91  ...   
1    83.0  0.91   82.0  0.91   82.0  0.91   83.0  0.91   81.0  0.91  ...   
2    81.0  0.91   81.0  0.92   81.0  0.92   81.0  0.91   81.0  0.91  ...   
3    81.0  0.91   81.0  0.91   81.0  0.91   81.0  0.91   81.0  0.91  ...   
4    81.0  0.91   81.0  0.91   81.0  0.91   81.0  0.91   81.0  0.91  ...   
..    ...   ...    ...   ...    ...   ...    ...   ...    ...   ...  ...   
90  184.0  0.86   42.0  0.92   42.0  0.92   42.0  0.92   42.0  0.92  ...   
91   42.0  0.92   42.0  0.92   42.0  0.92   42.0  0.92  208.0  0.88  ...   
92  353.0  1.00  352.0  1.00  352.0  1.00  353.0  1.00  352.0  1.00  ...   
93  358.0  1.00  358.0  1.00  358.0  1.00  358.0  1.00  358.0  1.00  ...   
94   42.0  0.92   42.0  0.92   42.0  0.93   42.0  0.92   42.0  0.92  ...   

    PF59    A60  PF60  fan  fridge  led  induction  laptop  toaster  washer  
0   0.91   82.0  0.91    1       0    0          0       0        0       0  
1   0.91   81.0  0.91    1       0    0          0       0        0       0  
2   0.91   81.0  0.91    1       0    0          0       0        0       0  
3   0.91   81.0  0.91    1       0    0          0       0        0       0  
4   0.91   81.0  0.91    1       0    0          0       0        0       0  
..   ...    ...   ...  ...     ...  ...        ...     ...      ...     ...  
90  0.92   42.0  0.92    0       0    0          0       0        0       1  
91  1.00  354.0  1.00    0       0    0          0       0        0       1  
92  1.00  357.0  1.00    0       0    0          0       0        0       1  
93  1.00   42.0  0.92    0       0    0          0       0        0       1  
94  0.90   37.0  0.90    0       0    0          0       0        0       1  

[95 rows x 127 columns]