In [2]:
import numpy as np

## Data types & Attributes

# Numpy's main data type is ndarray

In [2]:
a1= np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [42]:
a2= np.array([[1,2,3.3],[4,5,6.5]])
a2
a3=np.array([[[1,2,3],
            [4,5,6],
            [7,8,9]],
           [[10,11,12],
           [13,14,15],
           [16,17,18]]])

In [9]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [40]:
a3

NameError: name 'a3' is not defined

In [11]:
a1.shape

(3,)

In [12]:
a2.shape

(2, 3)

In [13]:
a3.shape

(2, 3, 3)

In [14]:
a1.ndim,a2.ndim,a3.ndim 

(1, 2, 3)

In [15]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [16]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [17]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# create a data frame from nump array

In [19]:
import pandas as pd

In [21]:
df = pd.DataFrame(a2)
df


0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# creating array

In [22]:
sample_array = np.array([1,2,3])

In [23]:
sample_array

array([1, 2, 3])

In [26]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
zeros = np.zeros((2,3))

In [28]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
range_array = np.arange(0,10,2)

In [30]:
range_array

array([0, 2, 4, 6, 8])

In [31]:
random_array = np.random.randint(0,10,size=(3,5))

In [32]:
random_array

array([[5, 3, 6, 9, 9],
       [2, 7, 9, 2, 4],
       [8, 1, 4, 2, 6]])

In [33]:
random_array2= np.random.random((5,3))
random_array2

array([[0.24765383, 0.93765813, 0.99721705],
       [0.82957104, 0.01891686, 0.36346429],
       [0.71962692, 0.7054764 , 0.76558741],
       [0.06840716, 0.17581556, 0.43650596],
       [0.24813756, 0.88787441, 0.06394845]])

In [34]:
random_array3 = np.random.rand(5,3)
random_array3

array([[0.71296401, 0.19822199, 0.90559033],
       [0.46411243, 0.51607644, 0.47893178],
       [0.3416254 , 0.79607209, 0.06022429],
       [0.62977832, 0.05826743, 0.86746919],
       [0.5274715 , 0.45593105, 0.25277977]])

In [6]:
#pseudorandom numbers,seed produce random numbers that are reproducable
a=np.random.seed(seed=0)
a

In [18]:
a=np.random.seed(seed=7)
random_array_4=np.random.randint(10,size=(5,3))
random_array_4

array([[4, 9, 6],
       [3, 3, 7],
       [7, 9, 7],
       [8, 9, 8],
       [7, 6, 4]])

In [21]:
a=np.random.seed(seed=7)
random_array_5=np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [22]:
random_array_5=np.random.random((5,3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

In [23]:
np.unique(random_array_4)

array([3, 4, 6, 7, 8, 9])

viewing array and matrices

In [24]:
random_array_4[0]

array([4, 9, 6])

In [25]:
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [26]:
a4.shape,a4.ndim

((2, 3, 4, 5), 4)

In [27]:
a4[:,:,:,:4]

array([[[[6, 7, 7, 9],
         [0, 7, 7, 7],
         [5, 4, 3, 1],
         [1, 3, 4, 3]],

        [[9, 5, 9, 1],
         [3, 2, 2, 5],
         [3, 0, 9, 9],
         [4, 5, 3, 0]],

        [[8, 6, 7, 2],
         [3, 8, 6, 6],
         [6, 5, 7, 1],
         [4, 4, 9, 9]]],


       [[[6, 2, 6, 8],
         [4, 1, 6, 1],
         [1, 6, 9, 8],
         [5, 9, 7, 5]],

        [[9, 6, 8, 1],
         [5, 8, 3, 7],
         [9, 4, 7, 5],
         [6, 2, 0, 5]],

        [[0, 5, 7, 1],
         [4, 9, 0, 2],
         [7, 6, 2, 9],
         [5, 1, 0, 0]]]])

 # Manipulating and comparing arrays

### Arithmatic 

In [30]:
ones= np.ones(3)

In [32]:
a1=np.array([1,2,3])

In [33]:
a1 + ones

array([2., 3., 4.])

In [34]:
a1-1 

array([0, 1, 2])

In [35]:
a1*ones


array([1., 2., 3.])

In [37]:
a2 = np.array([[1,4,9],[4,5,6]])

In [38]:
a2

array([[1, 4, 9],
       [4, 5, 6]])

In [39]:
a1*a2

array([[ 1,  8, 27],
       [ 4, 10, 18]])

In [43]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [44]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

numpy broadcast rules

In [45]:
a3  

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [46]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

reshape a2 for compatibility with a3

aggregation = performnig the same operation on a number of things

In [47]:
lisst_list = [1,2,3]

In [48]:
type(lisst_list)

list

In [49]:
sum(lisst_list)

6

In [50]:
a1

array([1, 2, 3])

In [51]:
type(a1)

numpy.ndarray

In [52]:
sum(a1)

6

In [55]:
np.sum(a1)

6

# use python method on python data types and use numpy method on numpy arrays

In [60]:
#create numpy array
massive_array = np. random.random(100000)

In [61]:
massive_array[:10]

array([0.40426013, 0.41530855, 0.48353827, 0.91425271, 0.26342942,
       0.33502027, 0.05236777, 0.3763368 , 0.26691994, 0.0892709 ])

In [62]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

21.8 ms ± 1.45 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
64.6 µs ± 389 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Cool!!!! therefore numpy methods are faster

.max,.min.mean,.var,.std(a) some of the methods

# reshaping and transposing

In [63]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [64]:
a3.shape()

TypeError: 'tuple' object is not callable

In [65]:
a3.shape(a3)

TypeError: 'tuple' object is not callable

In [66]:
a3.shape

(2, 3, 3)

In [67]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [68]:
a2.reshape(2,3,1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [69]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [70]:
a2_reshape= a2.reshape(2,3,1)

In [71]:
a2_reshape*a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

# transpose a.T

* -> element wise multiplication
. ->dot product np.dot()

np.dot(a1,a2)

In [76]:
np.random.seed(0)
sales_amounts = np.random.randint(20,size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

weekly)_sales = pd.DataFrame(sales_amount,index=['MON','TUE','WED','THU','FRI','SAT','SUN';])

In [77]:
A1

NameError: name 'A1' is not defined

In [78]:
a1

array([1, 2, 3])

In [79]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [80]:
a1>A2

NameError: name 'A2' is not defined

In [81]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [82]:
a1>=a2

array([[ True,  True, False],
       [False, False, False]])

sorting array

In [83]:
random_array = np.random.randint(10,size=(3,5))

In [84]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [85]:
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [86]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [87]:
np.argsort(random_array)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]], dtype=int64)

argsort gives index of sort values


argmin ,argmax

<img src="panda.png">

In [88]:
#turn image in numpy array

In [90]:
from matplotlib.image import imread

In [91]:
panda = imread("panda.png")

In [92]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [93]:
panda.shape

(2330, 3500, 3)