In [15]:
import numpy as np
import random
import pandas as pd
np.random.seed(196)

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
V1 = np.random.uniform(220.08,240.53,86400)
C1 = np.random.uniform(0.59,4.08,86400)
F1 = np.random.uniform(49.98,50.10,86400)
PF1 = np.random.uniform(0.691161,0.8,86400)
A1 = (V1*C1)/1.41421356237
AP1 = A1/PF1
RP1 = ((AP1**2)-(A1**2))**(1/2)

df = pd.DataFrame({'V1':V1,'C1':C1,'PF1':PF1,'AP1':AP1,'RP1':RP1,'F1':F1,'A1':A1})

In [18]:
from sklearn.ensemble import RandomForestRegressor
np.random.seed(42)

In [19]:
df.head()

V1        C1       PF1         AP1         RP1         F1  \
0  234.180465  2.956399  0.779041  628.402893  393.991280  50.048006   
1  231.899597  2.710027  0.759813  584.859973  380.241780  50.040194   
2  221.096090  1.298912  0.752028  270.029929  177.985267  50.082703   
3  223.742515  1.816916  0.719971  399.257646  277.086339  49.980744   
4  230.451922  1.276928  0.733568  283.655666  192.776928  50.099020   

           A1  
0  489.551905  
1  444.384267  
2  203.069957  
3  287.454046  
4  208.080736

In [20]:
X = df.drop('A1',axis = 1)
Y = df['A1']

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)

model = RandomForestRegressor()
model.fit(X_train,Y_train)

RandomForestRegressor()

In [21]:
model.score(X_test,Y_test)

0.999997883914399

In [31]:
df2 =pd.DataFrame({'V1': 280.08,'C1':0.64,'PF1':0.70,'AP1':180,'RP1':128.61,'F1':50.00},index=[0])

In [32]:
model.predict(df2)

array([108.56909447])

In [34]:
((108.56*24)/1000)*30

78.1632

In [35]:

X_test

V1        C1       PF1         AP1         RP1         F1
43404  231.704610  3.315743  0.723985  750.362823  517.612432  50.056850
78317  238.667730  3.621201  0.723002  845.263469  583.947144  50.054312
6096   229.015064  1.595588  0.795501  324.809799  196.819355  50.046732
40929  233.459311  3.872812  0.770823  829.407263  528.373131  50.021993
59505  222.864902  3.862764  0.750634  810.954359  535.812002  50.066755
...           ...       ...       ...         ...         ...        ...
51610  231.142302  1.602933  0.755714  346.674765  227.037898  50.038476
85047  232.392431  2.641886  0.794417  546.477575  331.915413  50.039743
47956  221.738785  3.896065  0.717648  851.218860  592.793747  49.988659
5780   222.132726  3.969352  0.790595  788.611388  482.897666  50.017718
52314  223.881925  2.586801  0.736711  555.866091  375.881205  50.041010

[17280 rows x 6 columns]

In [36]:
df3 =pd.DataFrame({'V1': 231.704610,'C1':3.315743,'PF1':0.723985,'AP1':750.362823,'RP1':517.612432,'F1':50.056850},index=[0])

In [38]:
model.predict(df3)

array([543.32193501])

In [40]:
Y_test

43404    543.251080
78317    611.126882
6096     258.386429
40929    639.326397
59505    608.730212
            ...    
51610    261.986995
85047    434.131201
47956    610.875700
5780     623.472345
52314    409.512431
Name: A1, Length: 17280, dtype: float64

In [41]:
V1 = np.random.uniform(220.08,240.53,86400)
C1 = np.random.uniform(0.59,4.08,86400)
PF1 = np.random.uniform(0.691161,0.8,86400)
A1 = (V1*C1)/1.41421356237

df4 = pd.DataFrame({'V1':V1,'C1':C1,'PF1':PF1,'A1':A1})

In [42]:
X = df4.drop('A1',axis = 1)
Y = df4['A1']

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)

model = RandomForestRegressor()
model.fit(X_train,Y_train)

RandomForestRegressor()

In [43]:
model.score(X_test,Y_test)

0.999998304470228

In [44]:
V1 = np.random.uniform(220.08,240.53,86400)
C1 = np.random.uniform(0.59,4.08,86400)
F1 = np.random.uniform(49.98,50.10,86400)
PF1 = np.random.uniform(0.691161,0.8,86400)
A1 = (V1*C1)/1.41421356237
AP1 = A1/PF1
RP1 = ((AP1**2)-(A1**2))**(1/2)

df5 = pd.DataFrame({'PF1':PF1,'AP1':AP1,'A1':A1})

In [45]:
X = df5.drop('A1',axis = 1)
Y = df5['A1']

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)

model = RandomForestRegressor()
model.fit(X_train,Y_train)
model.score(X_test,Y_test)

0.999997773115459

In [46]:
Y_test

31784    277.354222
62401    233.420458
64764    500.390418
17749    631.352951
57432    272.306112
            ...    
32852    202.948441
22711    469.909585
24439    649.571573
9730     403.208576
71353    599.983882
Name: A1, Length: 17280, dtype: float64

In [47]:
X_test

PF1         AP1
31784  0.711768  389.669296
62401  0.796512  293.053421
64764  0.783506  638.655827
17749  0.741518  851.433459
57432  0.737993  368.982101
...         ...         ...
32852  0.773728  262.299511
22711  0.713476  658.620205
24439  0.735568  883.088405
9730   0.752148  536.076186
71353  0.705077  850.948291

[17280 rows x 2 columns]

In [52]:
model.predict(pd.DataFrame({'PF1':0.711768,'AP1':389.669296},index=[0]))

array([277.43402962])